### ISSUE TITLE
Running Ledalab in batch mode leaves working directory in batch folder

### ISSUE THREAD

**Issue by bdyetton** [ledalab/ledalab#1]
After running Ledalab in matlab via the batch mode script the working directory is set to the location of the batch files to process. The user must add `cd('..')` to get back to the directory where Ledalab was run from. In my opinion, Ledalab should not change the working directory.

**Comment by tstenner** [comment]
Thanks, I'll take a look at it.

**Comment by tstenner** [comment]
Fixed in 5ed781143c6e39c30ef8b162f77ee0d7ae8f2308
