### ISSUE TITLE
Tips and suggestions for data analysis

### ISSUE THREAD

**Issue by lucameroll** [ledalab/ledalab#11]
Hello!
I am new to skin conductance analysis and Ledalab, so I am writing here hoping for some suggestions and tips regarding the matter. 
The purpose of my research is to detect SC responses (with Empatica E4) related to stress or arousal of the subject. Each session will last for about an hour and the events will be tagged, so most probably we'll have an event-related analysis. Anyway, for the moment I am just testing the E4, so the data acquired are about 30-40 minutes long and don't have tags. 
The processing steps I am following are: downsampling to 1 Hz and manual smoothing. I was also trying to apply a Butterworth low-pass filter, but seems like the system doesn't allow me so: do you know why?
After checking for artefacts, I proceed with the CDA and here I am really lost because of the number of variables in the file. Do you know how I can approach these datasets? What do those values mean and what are the most informative ones? 
Then given the fact that mine will be a within-subjects experiment, what do you think would be the most suited statistical tests to run?
I realise those are a load of questions (sorry about that!) but I am really new to these kinds of analyses so any suggestion will be greatly appreciated! :) 
Thank you very much in advance for your help!
Luca

**Comment by MatBenedek** [comment]
Note that sampling rate for EDA decomposition analyses is recommended to be 10Hz or higher (not sure if Empatica E4 enables this). In any case, down sampling is not recommended, and smoothing or filtering is usually not needed.

There is no clear advise on the best parameter, as different fields prefer different parameters. CDA.SCR should be very sensitive, but formal tests whether it is the best are not yet out there. Please also check the information on www.ledalab.de and the papers listed there. I'm sorry I cannot give formal advise on your statistical design, but onl offer technical help with Ledalab.

Mathias

**Comment by lucameroll** [comment]
Hello Mathias, 
Thank you for your reply and for your suggestions! So neither for an evant-related analysis is necessary to preprocess the data? Why is that? 
There's also one other thing I still cannot figure out, although the many posts on forums! I am trying to load some event tags but the csv file that Empatica gives me is not accepted by ledalab (although the conversion in UTC time, as suggested by Empatica support). What should I do to make it work? I see I have many options to load event markers, either in column in the EDA data spreadsheet or on their own (from File > Import events): which one is the quickest and easiest way, given that E4 data are different csv files containing just one measure (so either EDA or timestamps)?

Thank you very much for your support!

**Comment by MatBenedek** [comment]
Deally you get your data in the format as in the attached file. Then you can import it as Text Type 1. Time has to come in seconds, that is 0.0 not 00:00:00 format. And markers are best imported via a marker column in the same file (see example, column 3).

[ivn07_16.txt](https://github.com/ledalab/ledalab/files/4831778/ivn07_16.txt)

**Comment by lucameroll** [comment]
Thank you again!
