### ISSUE TITLE
Event Data for Empatica E4

### ISSUE THREAD

**Issue by TinasheMTapera** [ledalab/ledalab#8]
Hello,

We are using the empatica E4 to analyse EDA in ledalab and are confused as to how to load event-related data to calculate features during events. What format should the file be for event related data?

Best,

Tinashe

**Comment by MatBenedek** [comment]
Find infor on data import in the online documentation at http://www.ledalab.de/.
It also includes sample data files in Text or Matlab format.

Best
Mathias

**Comment by TinasheMTapera** [comment]
Forgot to close this, thanks
